name: unfold_ai_app
description: "A biometrics dashboard with clean architecture and BLoC state management."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
